storePassword.debug=karing
keyPassword.debug=karing
keyAlias.debug=karing
storeFile.debug=sign/karing.release.keystore

storePassword.release=karing
keyPassword.release=karing
keyAlias.release=karing
storeFile.release=sign/karing.release.keystore
